version: '3.8'

services:

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile-mariadb
    image: mariadb:inception
    volumes:
      - database:/var/lib/mysql
    env_file: ".env"
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    restart: unless-stopped
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile-wordpress
    image: wordpress:inception
    volumes:
      - www-data:/var/www/wp
    env_file: ".env"
    networks:
      - inception
    depends_on:
        mariadb:
          condition: service_started
        redis:
          condition: service_healthy
  
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: requirements/nginx
      dockerfile: Dockerfile-nginx
    image: nginx:inception
    volumes:
      - www-data:/var/www/wp
      - www-adminer:/var/www/adminer
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
        wordpress:
          condition: service_started
    
  adminer:
    container_name: adminer
    restart: unless-stopped
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile-adminer
    image: adminer:inception
    volumes:
      - www-adminer:/var/www/adminer
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_started

  vue-js:
    container_name: vue-js
    restart: unless-stopped
    build:
      context: requirements/bonus/vue-js
      dockerfile: Dockerfile-vuejs
    image: vue-js:inception
    networks:
      - inception
    ports:
      - 4848:4848

  redis:
    container_name: redis
    restart: unless-stopped
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile-redis
    image: redis:inception
    env_file: ".env"
    networks:
      - inception
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  vsftpd:
    container_name: vsftpd
    restart: unless-stopped
    build:
      context: requirements/bonus/vsftpd
      dockerfile: Dockerfile-vsftpd
    image: vsftpd:inception
    volumes:
      - www-data:/app/wordpress
    env_file: ".env"
    ports:
      - 20:20
      - 21:21
      - 990:990
      - 989:989
      - 30000-30010:30000-30010
    depends_on:
      wordpress:
        condition: service_started
    networks:
      - inception
  
  kuma:
    container_name: kuma
    restart: unless-stopped
    build:
      context: requirements/bonus/kuma
      dockerfile: Dockerfile-kuma
    image: kuma:inception
    volumes:
      - www-kuma:/app
    ports:
      - 3001:3001
    networks:
      - inception

networks:

  inception:

volumes:

  database:
    name: database
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

  www-data:
    name: www-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  
  www-adminer:
    name: www-adminer
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/adminer

  www-kuma:
    name: www-kuma
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/kuma


