FROM alpine:3.17

ARG M_USER=mysql

RUN addgroup -S -g 1000 ${M_USER} && adduser -S ${M_USER} -G ${M_USER}

RUN apk update -U && apk add --no-cache bash curl vim openrc mariadb mariadb-client

COPY ./conf/my.cnf /etc/mysql/my.cnf
COPY ./conf/my.cnf /etc/mysql/mariadb.conf.d/my.cnf
COPY ./conf/my.cnf /etc/my.cnf.d/mariadb-server.cnf

RUN mkdir -p /var/run/mysqld && \
    chown -R ${M_USER}:${M_USER} /var/run/mysqld && \
    chmod -R 755 /var/run/mysqld && \
    mkdir -p /var/lib/mysql && \
    chown -R ${M_USER}:${M_USER} /var/lib/mysql && \
    chmod -R 775 /var/lib/mysql && \
    mkdir -p /var/log/mysql && \
    chown -R ${M_USER}:${M_USER} /var/log/mysql && \
    chmod -R 755 /var/log/mysql && \
    mysql_install_db --user=${M_USER} --datadir=/var/lib/mysql

COPY ./tools/ .

RUN chown ${M_USER}:${M_USER} ./init.sh && \
    chmod +x ./init.sh

USER ${M_USER}:${M_USER}

EXPOSE 3306

ENTRYPOINT ["./init.sh"]
