FROM alpine:3.18

ARG MARIADB_VERSION=10.11.5-r0 \
    MARIADB_CLIENT_VERSION=10.11.5-r0 \
    M_USER=mysql

RUN apk update && \
	apk upgrade && \
	apk add bash && \
	apk add curl && \
	apk add vim && \
    apk add openrc && \
    apk add mariadb=${MARIADB_VERSION} && \
    apk add mariadb-client=${MARIADB_CLIENT_VERSION}

COPY ./conf/my.cnf /etc/mysql/my.cnf
COPY ./conf/my.cnf /etc/mysql/mariadb.conf.d/my.cnf
COPY ./conf/my.cnf /etc/my.cnf.d/mariadb-server.cnf

RUN mkdir -p /var/run/mysqld && \
    chown -R ${M_USER}:${M_USER} /var/run/mysqld && \
    chmod -R 755 /var/run/mysqld && \
    mkdir -p /var/lib/mysql && \
    chown -R ${M_USER}:${M_USER} /var/lib/mysql && \
    chmod -R 755 /var/lib/mysql && \
    mkdir -p /var/log/mysql && \
    chown -R ${M_USER}:${M_USER} /var/log/mysql && \
    chmod -R 755 /var/log/mysql

RUN mysql_install_db --user=${M_USER} --datadir=/var/lib/mysql

COPY ./tools/ .

RUN chown ${M_USER}:${M_USER} ./init.sh && \
    chmod +x ./init.sh

USER ${M_USER}:${M_USER}

ENTRYPOINT ["./init.sh"]
