FROM alpine:3.18

RUN apk update -U && \
    apk add --no-cache vim bash curl wget git nodejs npm && \
    npm install npm@9 -g && \
    mkdir app

COPY ./tools /

RUN chmod +x /init.sh

EXPOSE 3001

ENTRYPOINT ["./init.sh"]