FROM alpine:3.18

RUN apk update -U && apk add --no-cache vim bash curl wget git nodejs npm

RUN npm install -g @vue/cli && mkdir -p /var/www/static-site

COPY ./tools /var/www/static-site

WORKDIR /var/www/static-site

RUN chmod +x init.sh

EXPOSE 4848

ENTRYPOINT ["./init.sh"]