FROM alpine:3.18

ARG VUE_USER=vuejs-user

RUN addgroup -S -g 2011 ${VUE_USER} && adduser -S ${VUE_USER} -G ${VUE_USER}

RUN apk update -U && \
    apk add --no-cache vim bash curl wget git nodejs npm

RUN npm install -g @vue/cli

COPY ./tools /var/www/vue-app

WORKDIR /var/www/vue-app

RUN chown ${VUE_USER}:${VUE_USER} /var/www/vue-app/init.sh && \
    chmod +x /var/www/vue-app/init.sh && \
    chown -R ${VUE_USER}:${VUE_USER} /var/www/vue-app/ && \
    chmod -R 755 /var/www/vue-app/

USER ${VUE_USER}:${VUE_USER}

EXPOSE 4848

ENTRYPOINT ["./init.sh"]