FROM alpine:3.18

ARG NGINX_VERSION=1.24.0-r6 \
	OPENSSL_VERSION=3.1.3-r0 \
	C_USER=www-data

RUN delgroup ${C_USER} && addgroup -S -g 1981 ${C_USER} && adduser -S ${C_USER} -G ${C_USER}

RUN apk update -U && apk add --no-cache bash nginx=${NGINX_VERSION} openssl=${OPENSSL_VERSION} curl vim

RUN mkdir -p /etc/nginx/ssl && \
	openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=mmourdal.42.fr/UID=mmourdal" && \
	mkdir -p /var/run/nginx && \
	mkdir -p /var/log/nginx/wordpress && \
	touch /var/log/nginx/wordpress/access.log && \
	touch /var/log/nginx/wordpress/error.log && \
	mkdir -p /var/log/nginx/adminer && \
    touch /var/log/nginx/adminer/access.log && \
    touch /var/log/nginx/adminer/error.log && \
    mkdir -p /var/log/nginx/vuejs && \
    touch /var/log/nginx/vuejs/access.log && \
    touch /var/log/nginx/vuejs/error.log

COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN chmod -R 755 /var/lib/nginx && \
    chown -R ${C_USER}:${C_USER} /var/lib/nginx && \ 
    chmod -R 755 /var/log/nginx && \
    chown -R ${C_USER}:${C_USER} /var/log/nginx && \ 
    chmod -R 755 /var/run/nginx && \
    chown -R ${C_USER}:${C_USER} /var/run/nginx && \
    chmod -R 755 /etc/nginx && \
    chown -R ${C_USER}:${C_USER} /etc/nginx

USER ${C_USER}:${C_USER}

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]