FROM alpine:3.18

ARG REDIS_USER=redis-user

RUN addgroup -S ${REDIS_USER} && adduser -S ${REDIS_USER} -G ${REDIS_USER} && \
    apk update -U && apk add --no-cache vim bash curl wget redis redis-openrc

COPY ./conf /etc/

COPY ./tools /

RUN mkdir -p /var/lib/redis && \
    chown -R ${REDIS_USER}:${REDIS_USER} /var/lib/redis && \
    chmod -R 755 /var/lib/redis && \
    chown ${REDIS_USER}:${REDIS_USER} /etc/redis.conf && \
    chmod 755 /etc/redis.conf && \
    chown ${REDIS_USER}:${REDIS_USER} /init.sh && \
    chmod +x /init.sh

USER ${REDIS_USER}:${REDIS_USER}

EXPOSE 6379

ENTRYPOINT ["./init.sh"]